name = "septum"
description = "An interactive context-based text search tool for large codebases."
version = "0.0.1"

authors = ["Paul Jarrett"]
maintainers = ["Paul Jarrett <jarrett.paul.young@gmail.com>"]
maintainers-logins = ["pyjarrett"]

executables = ["septum"]
[[depends-on]]  # Added by alr
dir_iterators = "~0.0.2"  # Added by alr
[[depends-on]]  # Added by alr
progress_indicators = "~0.0.1"  # Added by alr
[[depends-on]]  # Added by alr
gnatcoll = "^21.0.0"  # Added by alr
