name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: CI on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:    
       - name: Checkout
         uses: actions/checkout@v2
       - name: pyjarrett/setup-alire
         uses: pyjarrett/setup-alire@latest-stable
       - name: Build
         run: |
          alr toolchain --install gnat_native
          alr build          
